### PR TITLE
Add -Wshadow to build_flags

### PR DESCRIPTION
**Pull request by whymarrh**
This PR adds [`-Wshadow`][1] to the build flags for the projects.

From [*Using the GNU Compiler Collection (GCC): Warning Options*][1]:

> `-Wshadow`
> Warn whenever a local variable or type declaration shadows another variable, parameter, type, class member (in C++), or instance variable (in Objective-C) or whenever a built-in function is shadowed. Note that in C++, the compiler warns if a local variable shadows an explicit typedef, but not if it shadows a struct/class/enum. Same as `-Wshadow=global`.
>
> `-Wshadow=global`
> The default for `-Wshadow`. Warns for any (global) shadowing.
>
> `-Wshadow=local`
> Warn when a local variable shadows another local variable or parameter. This warning is enabled by `-Wshadow=global`.
>
> `-Wshadow=compatible-local`
> Warn when a local variable shadows another local variable or parameter whose type is compatible with that of the shadowing variable. In C++, type compatibility here means the type of the shadowing variable can be converted to that of the shadowed variable. The creation of this flag (in addition to `-Wshadow=local`) is based on the idea that when a local variable shadows another one of incompatible type, it is most likely intentional, not a bug or typo, as shown in the following example:
> 
>     for (SomeIterator i = SomeObj.begin(); i != SomeObj.end(); ++i)
>     {
>       for (int i = 0; i < N; ++i)
>       {
>         ...
>       }
>       ...
>     }
> Since the two variable `i` in the example above have incompatible types, enabling only `-Wshadow=compatible-local` will not emit a warning. Because their types are incompatible, if a programmer accidentally uses one in place of the other, type checking will catch that and emit an error or warning. So not warning (about shadowing) in this case will not lead to undetected bugs. Use of this flag instead of `-Wshadow=local` can possibly reduce the number of warnings triggered by intentional shadowing.
>
> This warning is enabled by `-Wshadow=local`.

  [1]:https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

### CODE REVIEW

**Comment by arandell93** [comment]
What does it mean for a variable to shadow another?

**Comment by whymarrh** [comment]
The example in the OP is one:

```cpp
for (SomeIterator i = SomeObj.begin(); i != SomeObj.end(); ++i)
{
  for (int i = 0; i < N; ++i)
  {
    foo(i);
  }
  bar(i);
}
```

In the above code it is unclear whether `foo` is supposed to be called with the index (the inner `i`) or the outer iterator (the outer `i`).

A 2nd, more realistic, example could be the argument passed to the `errorReply` function in a few of the sketches.<sup>[\[1\]][1]</sup> The `errorReply` function takes a parameter `errorByte` but a variable with the same name exists in the global scope:

```cpp
uint8_t errorByte = 0;
// a few more variables
void errorReply(uint8_t errorByte);
```

Inside `errorReply` while it may be "clear" that references to `errorByte` are referring to the value passed in, if you were to remove that argument (or rename it and not its usages) the code would compile without error because usages of `errorByte` in the function body would switch to referencing the global `errorByte`.

Furthermore, places where you set the `errorByte` value and pass it into the `errorReply` are the only usages of the global `errorByte` and cause confusion about whether the value should be passed directly into the function or whether the `errorReply` function should reference the global variable. That is, this:

```cpp
bool reqCheck() {
  // ...
  if (reqCRC == byteToShort(reqLength-2)) {
    // ...
  } else {
    errorByte = 0x01;
    errorReply(errorByte);
    // ...
  }
}
```

The same could be achieved with either:

1. Passing the value directly

```cpp
bool reqCheck() {
  // ...
  if (reqCRC == byteToShort(reqLength-2)) {
    // ...
  } else {
    errorReply(0x01);
    // ...
  }
}
```

2. Having `errorReply` reference the global

```cpp
bool reqCheck() {
  // ...
  if (reqCRC == byteToShort(reqLength-2)) {
    // ...
  } else {
    errorByte = 0x01;
    errorReply();
    // ...
  }
}
```

Moving things out of the global scope is usually the preferred approach, so 1 might work best.

  [1]:https://git.io/vS53g
  [1]:https://travis-ci.org/LakeMaps/microcontrollers/jobs/222256373

**Comment by arandell93** [comment]
That makes more sense to me now. I guess it doesn't make sense to pass global variables into functions because they have knowledge of them anyway.

To your comment on preferring option 1 over the other, could you elaborate on it a bit? My first thought was that option 2 was preferable because it makes explicit what the meaning of 0x01 is (as it is defined in the API)

**Comment by whymarrh** [comment]
First, my apologies for that last bit of that comment. It should have read:

> Moving things out of the global scope is usually the preferred approach ~~so 1 might work best~~

Both options 1 and 2 work equally well.

*I* would prefer option 1 over option 2 because I (personally) side with the idea that global variables make the code difficult to follow.<sup>[\[1\]][1] [\[2\]][2] [\[3\]][3]</sup> While one can easily trace a chain of function calls (e.g. `foo` asks `bar` for the answer and `bar` returns `42`) it is (a bit) more difficult to follow what *side-effects* a chain of function calls have (e.g. `foo` calls `bar()` which returns 42 because `foo()` had told the world it was looking for the answer). With 100% less analogy:

```c
int16_t foo() {
    int16_t answer = bar("what is the answer to life the universe and everything?");
    return answer;
}
```

v.s.

```c
int16_t foo() {
    question = "what is the answer to life the universe and everything?";
    int16_t answer = bar();
    return answer;
}
```

(I don't know if that's 100% valid C but whatever.)

In isolation *I* would look at the 2nd and think to myself "huh, it looks like they're not even using the question." I'd be wrong though, 'cause unbeknownst to me `bar` answers whatever question was last asked by anyone in the world.

Does that make any sense?

If the idea of 1 strikes you as unclear because of the literal use of `0x01`, that's fine too. There's a solution to that!<sup>[\[4\]][4]</sup> What do you think of this[?][5]

```cpp
bool reqCheck() {
  // ...
  if (reqCRC == byteToShort(reqLength-2)) {
    // ...
  } else {
    errorReply(ERROR_MSG_FAILED_CRC);
    // ...
  }
}
```

hmmm

  [1]:https://softwareengineering.stackexchange.com/q/47923/114526
  [2]:https://softwareengineering.stackexchange.com/q/148108/114526
  [3]:https://softwareengineering.stackexchange.com/q/314660/114526
  [4]:http://wiki.c2.com/?MagicNumber
  [5]:https://i.imgur.com/A9yGtdW.gifv

**Comment by whymarrh** [comment]
But for realsies though, both options 1 and 2 work equally well.

**Comment by arandell93** [comment]
> If the idea of 1 strikes you as unclear because of the literal use of 0x01, that's fine too. There's a solution to that![4] What do you think of this?

So in that option, you explicitly define all of the literals you would pass into a function? I can get behind that, but I can also see where that would become obnoxious at the top of the file where you've got half the real number set (get it?) explicitly defined.

**Comment by whymarrh** [comment]
It's not uncommon to have a lot of named values (I spent a few minutes and found [1][1], [2][2], [3][3], [4][4], [5][5], [6][6], and [7][7])

  [1]:https://github.com/LowPowerLab/RFM69/blob/master/RFM69registers.h
  [2]:https://github.com/kr/beanstalkd/blob/v1.10/prot.c#L26-L139
  [3]:https://github.com/Netflix/eureka/blob/v1.6.2/eureka-client/src/main/java/com/netflix/appinfo/PropertyBasedInstanceConfigConstants.java
  [4]:https://github.com/Netflix/eureka/blob/v1.6.2/eureka-client/src/main/java/com/netflix/discovery/PropertyBasedClientConfigConstants.java
  [5]:https://git.io/vSFxy
  [6]:https://github.com/antirez/redis/blob/3.2.8/deps/lua/src/lopcodes.h#L34-L136
  [7]:https://github.com/antirez/redis/blob/3.2.8/deps/jemalloc/include/jemalloc/internal/witness.h#L9-L39

**Comment by arandell93** [comment]
Good enough. I can work with that then. I'll merge my branch tomorrow and then update that as well.

**Comment by whymarrh** [comment]
Arguably both option 1 and 2 would define a constant for `0x01`, where it's a special value.

**Comment by whymarrh** [comment]
If you agree with this change feel free to ~~like and subscribe~~ [approve](https://help.github.com/articles/approving-a-pull-request-with-required-reviews/) and [merge](https://help.github.com/articles/merging-a-pull-request/).

**Comment by arandell93** [comment]
Where do I click on the notification bell?

**Review by arandell93 — APPROVED** [review]
As discussed, going with option 1 in that we will pass variables directly and enumerate 'special numbers' for the purpose of avoiding the use of context-less numbers within the main body of the code.

**Pull request merged**
